import { getCssText } from "@/theme/stitches.config";

export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

      <style id="stitches" dangerouslySetInnerHTML={{ __html: getCssText() }} />
    </>
  )
}
